# This is the Ansible Galaxy requirements file to pull in the correct roles
# to support the operation of CASL provisioning/runs. 

# From 'casl-ansible'
- src: https://github.com/sherl0cks/casl-ansible
  scm: git
  version: unique-galaxy
  name: casl-ansible
